import json
import logging
import websocket
from typing import Dict, List, Optional, Tuple

from backend.src.clients.base_client import BaseAPIClient


class ComfyUIClient(BaseAPIClient):
    """
    Client for interacting with the ComfyUI API.
    Handles prompt queuing, image retrieval, and WebSocket communication.
    """

    def __init__(
        self,
        server_address: str,
        timeout: Optional[int] = 15,
        client_id: Optional[str] = None,
        logger: Optional[logging.Logger] = None
    ):
        super().__init__(
            server_address=server_address,
            timeout=timeout,
            client_id=client_id,
            logger=logger
        )

    def queue_prompt(self, prompt: Dict) -> Dict:
        """
        Sends the current workflow to the ComfyUI server to be queued.
        """
        payload = {"prompt": prompt, "client_id": self.client_id}
        print(f"[WORKFLOW NODES] {list(prompt.keys())}")
        output_nodes = [k for k, v in prompt.items() if v.get('class_type') in ['SaveImage', 'PreviewImage']]
        print(f"[OUTPUT NODES] {output_nodes}")
        node_40 = prompt.get('40', 'NOT FOUND')
        print(f"[NODE 40] {json.dumps(node_40)}")
        return self.http.post("/prompt", data=payload)

    def get_images(self, ws: websocket.WebSocket, prompt: Dict) -> Dict[str, List[bytes]]:
        """
        Retrieves images generated by the ComfyUI server after processing a prompt.
        """
        result = self.queue_prompt(prompt)

        if result.get("status") == "error":
            raise RuntimeError(f"Queue failed: {result['message']} | Detail: {result.get('detail', 'No detail')} | Data: {result.get('data', {})}")

        prompt_id = result["data"]["prompt_id"]
        output_images = {}
        current_node = ""

        while True:
            out = ws.recv()
            if isinstance(out, str):
                message = json.loads(out)
                if message["type"] == "executing":
                    data = message["data"]
                    if data["node"] is None and data["prompt_id"] == prompt_id:
                        break
                    else:
                        current_node = data["node"]
            else:
                if current_node not in output_images:
                    output_images[current_node] = []
                output_images[current_node].append(out[8:])

        return output_images

    def get_history(self, prompt_id: str) -> Dict:
        """
        Retrieves the generation history for a given prompt ID.
        """
        result = self.http.get(f"/history/{prompt_id}")
        return result.get("data", {})

    def get_queue(self) -> Dict:
        """
        Retrieves the current state of the ComfyUI queue.
        """
        result = self.http.get("/queue")
        return result.get("data", {})

    def interrupt(self) -> None:
        """
        Sends an interrupt request to stop the current ComfyUI execution.
        """
        self.http.post("/interrupt")

    def free_comfyui_memory(
        self,
        unload_models: bool = True,
        free_memory: bool = True,
        verbose: bool = False
    ) -> Dict:
        """
        Sends a request to free ComfyUI memory.
        """
        payload = {
            "unload_models": unload_models,
            "free_memory": free_memory,
        }
        if verbose:
            print(f"[ComfyUI] Freeing memory: {payload}")
        return self.http.post("/free", data=payload)

    def open_websocket_connection(self) -> Tuple[websocket.WebSocket, str, str]:
        """
        Opens a WebSocket connection to the ComfyUI server.
        """
        ws = websocket.WebSocket()
        ws.connect(f"ws://{self.server_address}/ws?clientId={self.client_id}")
        return ws, self.server_address, self.client_id
