server:
  fastapi_host: "127.0.0.1"
  fastapi_port: 8000
  comfyui_host: "127.0.0.1"
  comfyui_port: 8188

paths:
  comfyui_input_dir: "/workspace/ComfyUI_app/input"
  comfyui_output_dir: "/workspace/ComfyUI_app/output"
  project_images_dir: "/workspace/ImgGenScript/files/images"
  csv_dir: "/workspace/ImgGenScript/files/csv"
  workflow_dir: "backend/cfg/workflow"

prompts:
  special_characteristics_weight: 1.2

fullbody:
  workflow: "fullbody.json"
  checkpoint: "RealVisXL_V5.0_fp16.safetensors"
  batch_size: 1
  use_reference_pose: false
  k0_steps: 10
  k0_cfg: 10
  k0_sampler_name: "euler"
  k0_scheduler: "simple"
  dwpreprocessor_bbox_detector: "yolox_l.onnx"
  dwpreprocessor_pose_estimator: "dw-ll_ucoco_384_bs5.torchscript.pt"
  pose_controlnet_model: "diffusion_pytorch_model_promax.safetensors"
  pose_controlnet_weight: 1.0
  pose_controlnet_start: 0.0
  pose_controlnet_end: 1.0
  k1_steps: 10
  k1_cfg: 10
  k1_sampler_name: "euler"
  k1_scheduler: "simple"
  ipadapter_lora_name: "ip-adapter-faceid-plusv2_sdxl_lora.safetensors"
  ipadapter_lora_strength_model: 1.0
  ipadapter_lora_strength_clip: 1.0
  clip_vision_model: "CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors"
  insightface_model_name: "buffalo_l"
  faceid_loader_preset: "FACEID"
  faceid_loader_lora_strength: 1.0
  faceid_weight: 1.0
  faceid_v2_weight: 1.0
  faceid_weight_type: "linear"
  faceid_combine_embeds: "concat"
  faceid_start: 0.0
  faceid_end: 1.0
  plus_face_loader_preset: "STANDARD (medium strength)"
  plus_face_weight: 1.0
  plus_face_weight_type: "linear"
  plus_face_combine_embeds: "concat"
  plus_face_start: 0.0
  plus_face_end: 1.0
  k2_steps: 10
  k2_cfg: 10
  k2_sampler_name: "euler"
  k2_scheduler: "simple"
  k2_denoise: 1.0
  detailer_bbox_model: "bbox/face_yolov8m.pt"
  detailer_steps: 10
  detailer_cfg: 10
  detailer_sampler_name: "euler"
  detailer_scheduler: "simple"
  detailer_denoise: 1.0
  detailer_feather: 5
  detailer_bbox_threshold: 0.5
  detailer_bbox_dilation: 10
  detailer_bbox_crop_factor: 3.0
  detailer_drop_size: 10
  hands_refiner_mask_bbox_padding: 30
  hands_refiner_mask_type: "based_on_depth"
  hands_refiner_mask_expand: 5
  hands_refiner_detect_thr: 0.6
  hands_refiner_presence_thr: 0.6
  hands_refiner_controlnet_model: "diffusion_pytorch_model_promax.safetensors"
  hands_refiner_controlnet_weight: 1.0
  hands_refiner_controlnet_start: 0.0
  hands_refiner_controlnet_end: 1.0
  hands_refiner_steps: 10
  hands_refiner_cfg: 8.0
  hands_refiner_sampler_name: "euler"
  hands_refiner_scheduler: "simple"
  hands_refiner_denoise: 1.0

portrait:
  workflow: "portrait.json"
  checkpoint: "RealVisXL_V5.0_fp16.safetensors"
  batch_size: 1
  use_reference_pose: true
  controlnet_preprocessor: "DWPreprocessor"
  controlnet_preprocessor_sd_version: "sdxl"
  pose_controlnet_model: "diffusion_pytorch_model_promax.safetensors"
  pose_controlnet_weight: 1.0
  pose_controlnet_start: 0.0
  pose_controlnet_end: 1.0
  k1_steps: 10
  k1_cfg: 10
  k1_sampler_name: "euler"
  k1_scheduler: "simple"
  ipadapter_lora_name: "ip-adapter-faceid-plusv2_sdxl_lora.safetensors"
  ipadapter_lora_strength_model: 1.0
  ipadapter_lora_strength_clip: 1.0
  clip_vision_model: "CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors"
  insightface_model_name: "buffalo_l"
  faceid_loader_preset: "FACEID"
  faceid_loader_lora_strength: 1.0
  faceid_weight: 1.0
  faceid_v2_weight: 1.0
  faceid_weight_type: "linear"
  faceid_combine_embeds: "concat"
  faceid_start: 0.0
  faceid_end: 1.0
  plus_face_loader_preset: "STANDARD (medium strength)"
  plus_face_weight: 1.0
  plus_face_weight_type: "linear"
  plus_face_combine_embeds: "concat"
  plus_face_start: 0.0
  plus_face_end: 1.0
  k2_steps: 10
  k2_cfg: 10
  k2_sampler_name: "euler"
  k2_scheduler: "simple"
  k2_denoise: 1.0
  detailer_bbox_model: "bbox/face_yolov8m.pt"
  detailer_steps: 10
  detailer_cfg: 10
  detailer_sampler_name: "euler"
  detailer_scheduler: "simple"
  detailer_denoise: 1.0
  detailer_feather: 5
  detailer_bbox_threshold: 0.5
  detailer_bbox_dilation: 10
  detailer_bbox_crop_factor: 3.0
  detailer_drop_size: 10

generation_verbose: false
save_workflow: false
